server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/payflow_auth
    username: root
    password: Shivam@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: ${JWT_SECRET}   
  access-token-expiration: 900000      # 15 minutes (ms)
  refresh-token-expiration: 604800000  # 7 days (ms)
