server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_auth
    username: postgres
    password: Shivam@123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:default-super-secret-key}
  access-token-expiration: 900000
